#!/bin/bash
# height_res_array.sh — regenerate microclimate for ONE site at several
# height-tier spacings, for the height-resolution efficiency diagnostic.
#
# Chained sequentially via --dependency=afterok, not submitted independently:
# these share one ERA5-merged-file cache for $SITE (get_weather(), lib.R)
# with no locking around its extend/rename step, so running them
# concurrently can race on that shared file and silently corrupt it --
# 2026-07-24, exactly this happened to Saloya (three height-step jobs hit
# the ERA5 extend path within the same second; two manifests came back with
# 0 valid height tiers despite exiting 0).
#
# Usage: sbatch height_res_array.sh <SiteName>
# Run from: /home/s38leste_hpc/canopymicroenv/
#
#SBATCH --partition=intelsr_short
#SBATCH --account=ag_biob_scabral
#SBATCH --time=00:05:00
#SBATCH --ntasks=1
#SBATCH --output=/home/s38leste_hpc/canopymicroenv/logs/log_array_%j.out

SITE=${1:?"Usage: sbatch height_res_array.sh <SiteName>"}
N_MONTHS=12
HEIGHT_STEPS=(0.1 0.25 0.5 1.0)

prev_step_id=""
for step in "${HEIGHT_STEPS[@]}"; do
  if [ -n "$prev_step_id" ]; then
    dep_arg="--dependency=afterok:${prev_step_id}"
  else
    dep_arg=""
  fi

  JOB_SCRIPT=$(mktemp)
  cat > "$JOB_SCRIPT" <<'EOS'
#!/bin/bash
# Generated by height_res_array.sh -- run microclimate model for a single
# site at a single height step (mirrors microenv_array.sh's inner job).
#SBATCH --partition=lm_long
#SBATCH --account=ag_biob_scabral
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=1800G
#SBATCH --output=logs/run_microclimate_%j.log
#SBATCH --error=logs/run_microclimate_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=s38leste@uni-bonn.de
module purge
module load GCCcore/13.3.0
module load R/4.4.2-gfbf-2024a
module load Miniforge3/24.1.2-0
module load UDUNITS/2.2.28-GCCcore-13.2.0
export LD_LIBRARY_PATH="/opt/software/easybuild-INTEL/software/PROJ/9.3.1-GCCcore-13.2.0/lib:/opt/software/easybuild-INTEL/software/GDAL/3.9.0-foss-2023b/lib:/opt/software/easybuild-INTEL/software/GEOS/3.12.1-GCC-13.2.0/lib:$LD_LIBRARY_PATH"
unset PYTHONPATH
export LD_PRELOAD="/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libcrypto.so.3:/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libssl.so.3"
export CANOPY_PYTHON="/home/s38leste_hpc/.conda/envs/canopy_rgee/bin/python"
SITE=$1
N_MONTHS=${2:-12}
HEIGHT_STEP=${3:-0.1}
export CANOPY_SCRATCH=$(ws_allocate canopymicroenv 90)
echo "Scratch workspace: $CANOPY_SCRATCH"
cd /home/$USER/canopymicroenv
$CANOPY_PYTHON -c "import ee; print('ee import OK')" 2>&1
Rscript scripts/01_microclimate/run_microclimate_site.R "$SITE" "$N_MONTHS" "$HEIGHT_STEP"
EOS

  id=$(sbatch --parsable $dep_arg --job-name="microenv_${SITE}_h${step}" \
    "$JOB_SCRIPT" "$SITE" "$N_MONTHS" "$step")
  rm -f "$JOB_SCRIPT"
  echo "Submitted height step ${step}m for ${SITE}: job ${id}${dep_arg:+ (depends on $prev_step_id)}"
  prev_step_id="$id"
done
echo "LAST_JOB_ID=${prev_step_id}"