#!/bin/bash
# microenv_array.sh — submit one job per site to the Marvin cluster
# Usage: sbatch microenv_array.sh [n_months] [height_step] [single_site]
#   e.g. sbatch microenv_array.sh 12 0.5                  # all sites
#   e.g. sbatch microenv_array.sh 12 0.5 Maquipucuna       # one site only
#        (this is what run_microclimate.sh's `submit-site` uses)
# Run from: /home/s38leste_hpc/canopymicroenv/
#
# Per-site jobs used to delegate to a separate run_microenv.sh template
# file; that file was redundant with the loop body here and has been
# removed. Each iteration now writes its own throwaway job script (via
# mktemp) carrying the #SBATCH directives SLURM requires at the top of the
# submitted file, submits it, and deletes it -- sbatch has already read and
# stored the script content by the time it returns, so the temp file isn't
# needed afterward.
#
# NOTE: run_microclimate_site.R now uses the canopy-height raster (vhgt.tif)
# as the height ceiling, not the tallest recorded epiphyte observation — the
# ceiling can be much taller than before (e.g. Maquipucuna: ~5.5m -> ~15m).
# At height_step=0.1 that's ~3x more height tiers, and each tier is a real
# microclimf run — consider a coarser step (0.25-0.5m) for practicality.
# Existing unsuffixed microenv_<site>.rds manifests (from the old, truncated
# ceiling) must be deleted or moved first, or the script will see them and
# exit immediately without regenerating anything — see check_microenv_progress.R.
#
# NOTE (2026-07-22): MiradorMindo retired -- its raw GeoJSON export actually
# bundled observations from 3 separate locations. Replaced here by
# LaElenita/MindoMirador/Saloya (see scripts/00_data_conversion/rebuild_combined_csv.py). This
# only takes effect once combinedv3.csv itself has been updated with those
# site names (make_sites() in lib.R groups by Area_or_Site in
# combinedv3.csv, not by this array) -- promote the split rows from
# combined.csv into combinedv3.csv (with species IDs) before submitting.
# Every other pipeline script derives its site list dynamically from the
# observations CSV, so the new sites are picked up automatically. The one
# exception is scripts/legacy/allsites.R, which still hardcodes the old
# 5-site list incl. "MiradorMindo" -- it predates the site split entirely
# and is not part of the active pipeline (see its own header comment).
#
#SBATCH --partition=intelsr_short
#SBATCH --account=ag_biob_scabral
#SBATCH --time=00:01:00
#SBATCH --ntasks=1
#SBATCH --output=/home/s38leste_hpc/canopymicroenv/logs/log_array_%j.out

SITES=("Maquipucuna" "Mashpi" "MindoTarabita" "LaElenita" "MindoMirador" "Saloya" "Yanayacu")
N_MONTHS=${1:-12}      # e.g. sbatch microenv_array.sh 12
HEIGHT_STEP=${2:-0.1}  # e.g. sbatch microenv_array.sh 12 0.5
SINGLE_SITE=${3:-}     # e.g. sbatch microenv_array.sh 12 0.5 Maquipucuna -- restrict to one site

if [ -n "$SINGLE_SITE" ]; then
  SITES=("$SINGLE_SITE")
fi

for i in "${!SITES[@]}"; do
  SITE="${SITES[$i]}"
  JOB_SCRIPT=$(mktemp)
  cat > "$JOB_SCRIPT" <<'EOS'
#!/bin/bash
# Generated by microenv_array.sh -- run microclimate model for a single site.
#SBATCH --partition=lm_long
#SBATCH --account=ag_biob_scabral
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=1800G
#SBATCH --output=logs/run_microclimate_%j.log
#SBATCH --error=logs/run_microclimate_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=s38leste@uni-bonn.de

module purge
module load GCCcore/13.3.0
module load R/4.4.2-gfbf-2024a
module load Miniforge3/24.1.2-0
module load UDUNITS/2.2.28-GCCcore-13.2.0
export LD_LIBRARY_PATH="/opt/software/easybuild-INTEL/software/PROJ/9.3.1-GCCcore-13.2.0/lib:/opt/software/easybuild-INTEL/software/GDAL/3.9.0-foss-2023b/lib:/opt/software/easybuild-INTEL/software/GEOS/3.12.1-GCC-13.2.0/lib:$LD_LIBRARY_PATH"
unset PYTHONPATH
export LD_PRELOAD="/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libcrypto.so.3:/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libssl.so.3"
export CANOPY_PYTHON="/home/s38leste_hpc/.conda/envs/canopy_rgee/bin/python"

SITE=$1      # e.g. "Maquipucuna"
N_MONTHS=${2:-12}  # months of ERA5 to fetch backwards from tme_end (default: 12, matches run_microclimate_site.R's own default and the rest of the pipeline's annual climate resolution)
HEIGHT_STEP=${3:-0.1}  # m between height tiers (default: 0.1, production resolution)

# Allocate (or find existing) Lustre workspace for per-height temp files.
# ws_allocate is idempotent: calling it again returns the same path.
export CANOPY_SCRATCH=$(ws_allocate canopymicroenv 90)
echo "Scratch workspace: $CANOPY_SCRATCH"

cd /home/$USER/canopymicroenv
$CANOPY_PYTHON -c "import ee; print('ee import OK')" 2>&1
Rscript scripts/01_microclimate/run_microclimate_site.R "$SITE" "$N_MONTHS" "$HEIGHT_STEP"
EOS
  sbatch --job-name="microenv_${SITE}" "$JOB_SCRIPT" "$SITE" "$N_MONTHS" "$HEIGHT_STEP"
  rm -f "$JOB_SCRIPT"
done
