#!/bin/bash
# microenv_array.sh — submit one job per site to the Marvin cluster
# Usage: sbatch microenv_array.sh [n_months] [height_step] [single_site] [exclude_site]
#   e.g. sbatch microenv_array.sh 12 0.5                       # all sites
#   e.g. sbatch microenv_array.sh 12 0.5 Maquipucuna            # one site only
#        (this is what run_microclimate.sh's `submit-site` uses)
#   e.g. sbatch microenv_array.sh 12 0.25 "" Maquipucuna        # all sites except one
# Run from: /home/s38leste_hpc/seres/
#
# 2026-08-04: rewritten to chain sites sequentially via --dependency=afterok
# instead of submitting every site's height-loop job simultaneously.
# Previously all sites launched at once, each independently writing
# hundreds of per-height climate TIFFs into the shared Lustre scratch
# workspace at the same time -- 2026-08-04, this filled the shared
# filesystem (91% used cluster-wide) and caused every one of that night's
# 7 site jobs to fail with "No space left on device" simultaneously, none
# completing more than ~20% of their heights. Sequential chaining means
# only one site's height-loop writes to scratch at a time.
#
# NOTE: run_microclimate_site.R now uses the canopy-height raster (vhgt.tif)
# as the height ceiling, not the tallest recorded epiphyte observation — the
# ceiling can be much taller than before (e.g. Maquipucuna: ~5.5m -> ~15m).
# At height_step=0.1 that's ~3x more height tiers, and each tier is a real
# microclimf run — consider a coarser step (0.25-0.5m) for practicality.
# Existing unsuffixed microenv_<site>.rds manifests (from the old, truncated
# ceiling) must be deleted or moved first, or the script will see them and
# exit immediately without regenerating anything — see check_microenv_progress.R.
#
#SBATCH --partition=intelsr_short
#SBATCH --account=ag_biob_scabral
#SBATCH --time=00:05:00
#SBATCH --ntasks=1
#SBATCH --output=/home/s38leste_hpc/seres/logs/log_array_%j.out

SITES=("Maquipucuna" "Mashpi" "MindoTarabita" "LaElenita" "MindoMirador" "Saloya" "Yanayacu")
N_MONTHS=${1:-12}
HEIGHT_STEP=${2:-0.1}
SINGLE_SITE=${3:-}
EXCLUDE_SITE=${4:-}     # e.g. sbatch microenv_array.sh 12 0.25 "" Maquipucuna -- skip one site

if [ -n "$SINGLE_SITE" ]; then
  SITES=("$SINGLE_SITE")
elif [ -n "$EXCLUDE_SITE" ]; then
  NEW_SITES=()
  for s in "${SITES[@]}"; do
    if [ "$s" != "$EXCLUDE_SITE" ]; then
      NEW_SITES+=("$s")
    fi
  done
  SITES=("${NEW_SITES[@]}")
fi

# 2026-08-14: vlmnode219 drained by node health check ("MCEs detected -
# 3 UNcorrected memory errors") -- the confirmed hardware cause of the 5
# unrelated SIGBUS crashes that killed job 26959283 after 76h at 66/76
# heights. SLURM already refuses to schedule a drained node; this is
# belt-and-braces against it being un-drained mid-chain (the chain runs
# for days). Override at submit time:
#   EXCLUDE_NODES= sbatch microenv_array.sh 12 0.4 Maquipucuna    # lift it
#   EXCLUDE_NODES=vlmnode219,vlmnode220 sbatch ...                # extend
EXCLUDE_NODES=${EXCLUDE_NODES-vlmnode219}
excl_arg=${EXCLUDE_NODES:+--exclude=${EXCLUDE_NODES}}

prev_job_id=""
for i in "${!SITES[@]}"; do
  SITE="${SITES[$i]}"

  if [ -n "$prev_job_id" ]; then
    dep_arg="--dependency=afterok:${prev_job_id}"
  else
    dep_arg=""
  fi

  JOB_SCRIPT=$(mktemp)
  cat > "$JOB_SCRIPT" <<'EOS'
#!/bin/bash
# Generated by microenv_array.sh -- run microclimate model for a single site.
# 2026-08-09: moved from lm_long/1800G to vlm_long/3000G -- the mc.cores=4
# height loop (run_microclimate_site.R now uses method="Cpp", confirmed
# numerically identical to "R" but ~8% faster) OOM'd at both 900G and 1500G
# in diagnostic testing (diag_wrap_concurrency.R), peaking near 1494GB with
# only 1-2 of 4 workers still alive -- memory pressure here scales with
# more than just concurrent worker count, so headroom matters more than the
# node count; vlm's ~3.9TB/node gives real margin vs. lm's ~1.95TB/node cap.
#SBATCH --partition=vlm_long
#SBATCH --account=ag_biob_scabral
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=3000G
#SBATCH --requeue
#SBATCH --output=logs/run_microclimate_%j.log
#SBATCH --error=logs/run_microclimate_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=s38leste@uni-bonn.de
module purge
module load GCCcore/13.3.0
module load R/4.4.2-gfbf-2024a
module load Miniforge3/24.1.2-0
module load UDUNITS/2.2.28-GCCcore-13.2.0
export LD_LIBRARY_PATH="/opt/software/easybuild-INTEL/software/PROJ/9.3.1-GCCcore-13.2.0/lib:/opt/software/easybuild-INTEL/software/GDAL/3.9.0-foss-2023b/lib:/opt/software/easybuild-INTEL/software/GEOS/3.12.1-GCC-13.2.0/lib:$LD_LIBRARY_PATH"
unset PYTHONPATH
export LD_PRELOAD="/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libcrypto.so.3:/home/s38leste_hpc/.conda/envs/canopy_rgee/lib/libssl.so.3"
export CANOPY_PYTHON="/home/s38leste_hpc/.conda/envs/canopy_rgee/bin/python"
SITE=$1
N_MONTHS=${2:-12}
HEIGHT_STEP=${3:-0.1}
export CANOPY_SCRATCH=$(ws_allocate seres 90)
echo "Scratch workspace: $CANOPY_SCRATCH"
# 2026-08-10: node-local /tmp filled up during Maquipucuna's first
# production run (terra's wrap/unwrap/resample/mask scratch rasters,
# never cleaned up across 76 heights x 4 concurrent workers), silently
# truncating that site's manifest to 16/76 heights -- see
# run_microclimate_site.R's terraOptions() call for the R-side half of
# this fix. Route R's tempdir (and therefore terra's) onto the much
# larger Lustre scratch workspace instead.
mkdir -p "$CANOPY_SCRATCH/tmp"
export TMPDIR="$CANOPY_SCRATCH/tmp"
cd /home/$USER/seres
$CANOPY_PYTHON -c "import ee; print('ee import OK')" 2>&1
Rscript scripts/01_microclimate/run_microclimate_site.R "$SITE" "$N_MONTHS" "$HEIGHT_STEP"
EOS

  id=$(sbatch --parsable $dep_arg $excl_arg --job-name="microenv_${SITE}" \
    "$JOB_SCRIPT" "$SITE" "$N_MONTHS" "$HEIGHT_STEP")
  rm -f "$JOB_SCRIPT"
  echo "Submitted ${SITE}: job ${id}${dep_arg:+ (depends on $prev_job_id)}"
  prev_job_id="$id"
done
echo "LAST_JOB_ID=${prev_job_id}"